// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCore.Infraestructure.Persistence;

namespace NetCore.WebAPI.Migrations
{
    [DbContext(typeof(NetCoreContext))]
    partial class NetCoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NetCore.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .HasColumnType("VARCHAR(150)");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("sysdatetime()")
                        .HasDefaultValueSql("sysdatetime()");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("sysdatetime()");

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime>("FechaNaciemiento")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Nombre")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Telefono")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("ADM_Cliente");
                });

            modelBuilder.Entity("NetCore.Domain.Entities.Detalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("INT");

                    b.Property<int>("IdFactura")
                        .HasColumnType("INT");

                    b.Property<int>("IdProducto")
                        .HasColumnType("INT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ADM_Detalle");
                });

            modelBuilder.Entity("NetCore.Domain.Entities.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo_Control")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int>("Codigo_Tarjeta")
                        .HasColumnType("INT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("DATETIME");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INT");

                    b.Property<decimal>("Importe")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("Modo_Pago")
                        .HasColumnType("INT");

                    b.Property<int>("Nit")
                        .HasColumnType("INT");

                    b.Property<string>("Razon_Social")
                        .HasColumnType("VARCHAR(MAX)");

                    b.HasKey("Id");

                    b.ToTable("ADM_Factura");
                });

            modelBuilder.Entity("NetCore.Domain.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidoMaterno");

                    b.Property<string>("ApellidoPaterno");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("ADM_Persona");
                });

            modelBuilder.Entity("NetCore.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Costo")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("Nombre")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("Stock")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ADM_Producto");
                });

            modelBuilder.Entity("NetCore.Domain.Entities.Cliente", b =>
                {
                    b.OwnsOne("NetCore.Domain.ValueObject.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<int>("ClienteId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Barrio")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("Barrio")
                                .HasMaxLength(100)
                                .HasDefaultValue("");

                            b1.Property<string>("Calle")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("Calle")
                                .HasMaxLength(100)
                                .HasDefaultValue("");

                            b1.Property<int>("Numero")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("Numero")
                                .HasDefaultValue(1);

                            b1.HasKey("ClienteId");

                            b1.ToTable("ADM_Cliente");

                            b1.HasOne("NetCore.Domain.Entities.Cliente")
                                .WithOne("Direccion")
                                .HasForeignKey("NetCore.Domain.ValueObject.Direccion", "ClienteId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
